on: push
name: Build
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@master
      with:
        name: Debug APK
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: ./app/build/outputs/apk/debug/app-debug.apk
